version: "3.8"
    
services:
  consul:
    image: consul:1.8.3
    volumes:
      - ./config:/config
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0 -config-file /config/consul.hcl"
  vault:
    image: vault:1.5.2
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK

  consul_template:
    image: hashicorp/consul-template:light
    environment:
      CONSUL_HTTP_ADDR: consul:8500
      CT_LOCAL_CONFIG: |
        template {
          contents = <<EOH
        {{ range ls "app" }}
        {{ .Key }}={{ .Value }}{{ end }}
        EOH
          destination = "/tmp/app-values"
          wait {
            min = "2s"
            max = "5s"
          }
        }
    volumes:
      - "./values:/tmp"
